source: src
destination: _site

include:
  - assets

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: "Jared's Art Blog"
url: "https://jaredsartblog.net"
description: "A blog about oil painting, watercolor, and photography by Jared Perkins"
author: "Jared Perkins"